name: meraki
description: Player de músicas locais, Subsonic e Jellyfin para Android, Linux e Windows.
publish_to: none
version: 1.3.7+9

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  audio_service: ^0.18.19
  audio_service_win: 0.0.3
  audio_service_mpris: ^0.2.1
  file_picker: ^12.1.1
  audio_session: ^0.2.4
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.13.0
  just_audio: ^0.10.6
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.6
  package_info_plus: ^10.2.1
  permission_handler: ^12.0.1
  phosphoricons_flutter: ^1.0.0
  rust_lib_meraki:
    path: rust_builder
  rxdart: ^0.28.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/meraki_mark.png
    - assets/videos/welcome_background_optimized.mp4
    - assets/images/welcome_poster.webp
  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-400.ttf
        - asset: assets/fonts/PixelifySans-500.ttf
          weight: 500
        - asset: assets/fonts/PixelifySans-600.ttf
          weight: 600
        - asset: assets/fonts/PixelifySans-700.ttf
          weight: 700
